version: 2
updates:
  - package-ecosystem: gomod # Go modules
    directory: / # Location of package manifests
    schedule:
      interval: daily
    allow:
      # Allow both direct and indirect dependencies
      - dependency-type: all
